### PR TITLE
Prepare for waf 1.8.8

### PR DESCRIPTION
**Pull request by jpihl**

### CODE REVIEW

**Comment by jpihl** [comment]
Any comments? I did this so that we can upgrade to the new version of Waf, but the changes also works with the current waf version.

@mortenvp @petya2164

**Comment by mortenvp** [comment]
The ``get_cc_version`` is that a waf function? In general I don't like that we have to pass all those bools around. What is the content of the parameter ``compiler`` passed to e.g. it is not specified in the doc string ``mkspec_check_minimum_cc_version``?

**Comment by jpihl** [comment]
yes, ``get_cc_version`` is a waf function. I also don't like the bool stuff. And it's actually worse in waf since ``get_cc_version`` also takes a third bool called ``icc`` for the intel compiler :confused:.
I chose to do it the same way as waf beacuse it was easier and seemed more safe.

The content of the ``compiler`` parameter is the path to the compiler we want to check, e.g,:
* ``/usr/bin/gcc``
* ``/usr/bin/gcc-4.8``
* ``/usr/bin/g++``
* ``/usr/bin/clang``
* ``/home/user/dev/arm-linux-androideabi-4.8/bin/arm-linux-androideabi-g``

and so on.. So you could maybe something like this:
```
gcc = "gcc" in compiler
clang = "clang" in compiler
```
instead of having the parameters. It just seems a little more unsafe. What do you think?

**Comment by petya2164** [comment]
Yeah, I agree with Morten. Passing those bools is not pretty ;)
Btw, I already tried to upgrade to waf 1.8.5 in the dep-recursion branch, and the following changes were necessary:
https://github.com/steinwurf/waf-tools/commit/5ab9a784ddaae90772e022e785913c664909cc36
Perhaps we should finish the restructuring of waf-tools and the dependency management before we do any major changes here, otherwise it will be difficult to merge...

**Comment by jpihl** [comment]
I wanted to upgrade waf due to issues with kodo-python, python3 and mac os. For that reason, I didn't run into issues with the runners yet. I can incorporate those changes as well.

The last changes in the dep-recursion branch is 3 months old. I don't know how far it is from being finished, but I don't like the idea of "locking down" a repository for such a long time.

**Comment by mortenvp** [comment]
We can make a ``compiler_info`` object which contains path, name etc. and then pass that around.. Then you avoid the slightly dodgy:
```
if 'clang' in compiler:
```
It just becomes:
```
if 'clang' == compiler.name:
```

What do you think?

I'm also not settled on the dependency resolve stuff - I think it needs more time/thinking..

**Comment by petya2164** [comment]
Let's solve this problem by eliminating the problem:
We can move our check_version functions from cxx_common to gxx_common and clang_common. Then we don't have to pass around any booleans. Furthermore, we can combine check_version and check_minimum_version into a single function. There is no need to have 2 variants.

**Comment by petya2164** [comment]
Check out my simplified solution. No boolean magic required ;)
And we are safe if Thomas decides to create separate functions for checking gcc and clang versions (I guess he should do that to avoid those messy ifs).

**Comment by mortenvp** [comment]
I just got around to looking at this :) nice solution @petya2164

**Pull request merged**
