### PR TITLE
Add mkspec for Emscripten 1.27 and 1.30

### PR DESCRIPTION
**Pull request by FeherMarcell**
Please add an official make specification for Emscripten version 1.27

### CODE REVIEW

**Comment by petya2164** [comment]
@FeherMarcell Thanks for the contribution! I will test and merge this soon.
Are you only using the latest version at this point?
Maybe we should implement a more generic mkspec for emscripten that would only check the minimum required version. Then we don't have to write one for each minor version. What do you think?

**Comment by mortenvp** [comment]
I like that idea - but I think that it is important that you can run with a specific version also. Mainly for testing purposes. It is nice to  know specifically which versions it is tested with. 

So in similar spirit as our cxx_mkspecs where a developer most of the time uses the default one. But the build system uses specific ones - so we know which compiler etc. is the problem in case of failure.

**Comment by jpihl** [comment]
We already have ``cxx_default``, ``cxx_default_x32``, and ``cxx_default_x64``. Maybe we should solve this by adding ``cxx_default_emscripten``?
But I agree with Morten that we still need the specific mkspecs for the buildbot.

**Comment by petya2164** [comment]
I vote for cxx_default_emscripten! It could check for the minimum supported version.
It just feels to very tedious to add these specs for all the minor versions, they are coming out much faster than the "regular" compiler versions.
And you should also consider that emscripten is not running on the buildbot for compatibility reasons ;)

**Comment by FeherMarcell** [comment]
I agree, a default mkspec would be convenient for the developer.
@petya2164 I'm currently using Emscripten 1.27, but I was experimenting with 1.30 too. Kodo behaved well in both cases for me, but I didn't do extensive testing.

**Comment by petya2164** [comment]
@FeherMarcell Thanks for the feedback!
I think cxx_default_emscripten should check for version 1.25 as a minimum, since that one worked fine.
Then you won't need a new mkspec if you upgrade in the future ;)

**Comment by petya2164** [comment]
I added cxx_default_emscripten in our waf-tools. It should be convenient in the future.

**Pull request merged**
